<?php
// public/send_invoice_email.php
ini_set('display_errors', 1);
error_reporting(E_ALL);

require_once __DIR__ . '/includes/db.php';
require_once __DIR__ . '/includes/functions.php';
require_once __DIR__ . '/includes/mail.php';

if (session_status() === PHP_SESSION_NONE) session_start();

// Fix: correct log file path (now inside public_html)
$logFile = __DIR__ . '/invoice_debug.txt';

// Fix: ensure JSON response header
header('Content-Type: application/json');

// === Logging helper ===
function log_invoice($msg) {
    global $logFile;
    file_put_contents($logFile, "[" . date('Y-m-d H:i:s') . "] [send_invoice_email] $msg\n", FILE_APPEND);
}

$order_id = isset($_GET['order_id']) ? (int)$_GET['order_id'] : 0;
if (!$order_id) {
    log_invoice("❌ Missing order_id in request");
    http_response_code(400);
    echo json_encode(['status' => 'error', 'message' => 'Missing order_id']);
    exit;
}

// === Fetch order ===
$stmt = $pdo->prepare("SELECT * FROM orders WHERE id = ? LIMIT 1");
$stmt->execute([$order_id]);
$order = $stmt->fetch(PDO::FETCH_ASSOC);

if (!$order) {
    log_invoice("❌ Order not found for ID $order_id");
    echo json_encode(['status' => 'error', 'message' => 'Order not found']);
    exit;
}

// === Fetch order items ===
$stmt_items = $pdo->prepare("
    SELECT oi.*, COALESCE(p.name, oi.product_name) AS name
    FROM order_items oi
    LEFT JOIN products p ON oi.product_id = p.id
    WHERE oi.order_id = ?
");
$stmt_items->execute([$order_id]);
$items = $stmt_items->fetchAll(PDO::FETCH_ASSOC);
if (!$items) {
    log_invoice("⚠ No items found for order $order_id");
}

// === Build Invoice HTML ===
$total = 0;
$invoiceHtml = "
<h2 style='color:#28a745;'>Avoji Foods Invoice</h2>
<p>Dear <strong>" . htmlspecialchars($order['name']) . "</strong>,</p>
<p>Thank you for shopping with <strong>Avoji Foods</strong>! Here are your order details:</p>
<p><strong>Order ID:</strong> #" . htmlspecialchars($order['id']) . "<br>
<strong>Date:</strong> " . htmlspecialchars($order['created_at']) . "<br>
<strong>Shipping Address:</strong><br>" . nl2br(htmlspecialchars($order['shipping_address'])) . "</p>
<table border='1' cellpadding='8' cellspacing='0' style='border-collapse:collapse;width:100%;margin-top:15px;'>
<thead style='background:#f8f9fa;'>
<tr><th>Product</th><th>Qty</th><th>Price</th><th>Subtotal</th></tr>
</thead><tbody>";

foreach ($items as $item) {
    $subtotal = $item['price'] * $item['quantity'];
    $total += $subtotal;
    $invoiceHtml .= "<tr>
        <td>" . htmlspecialchars($item['name']) . "</td>
        <td align='center'>" . (int)$item['quantity'] . "</td>
        <td align='right'>₹" . number_format($item['price'], 2) . "</td>
        <td align='right'>₹" . number_format($subtotal, 2) . "</td>
    </tr>";
}

$invoiceHtml .= "</tbody>
<tfoot><tr><th colspan='3' align='right'>Grand Total</th>
<th align='right'>₹" . number_format($total, 2) . "</th></tr></tfoot>
</table>
<br><p>We hope you enjoy your order!<br><strong>Avoji Foods</strong></p>";

// === Recipient Emails ===
$billingEmail = $order['email'];
$accountEmail = $_SESSION['user']['email'] ?? null;
$recipients = array_unique(array_filter([$billingEmail, $accountEmail]));
$adminEmail = 'ahmad@webshigh.com';

try {
    // === Send to customers ===
    foreach ($recipients as $recipient) {
        $success = send_email($recipient, "Your Avoji Foods Invoice (Order #$order_id)", $invoiceHtml);
        log_invoice(($success ? "✅" : "❌") . " Invoice " . ($success ? "sent" : "failed") . " to $recipient");
    }

    // === Send to admin ===
    $adminBody = "
        <h3>🧾 New Invoice Generated</h3>
        <p><strong>Order ID:</strong> #$order_id</p>
        <p><strong>Customer:</strong> " . htmlspecialchars($order['name']) . "</p>
        <p><strong>Billing Email:</strong> " . htmlspecialchars($order['email']) . "</p>
        <p><strong>Total:</strong> ₹" . number_format($total, 2) . "</p>
        <hr><p>Auto-generated by Avoji Foods System.</p>";

    $adminStatus = send_email($adminEmail, "🧾 Invoice Generated (#$order_id)", $adminBody);
    log_invoice($adminStatus ? "📧 Admin invoice email sent" : "❌ Failed to send admin email");

    echo json_encode(['status' => 'ok', 'message' => 'Invoice emails sent']);

} catch (Throwable $e) {
    log_invoice("❌ Exception: " . $e->getMessage());
    echo json_encode(['status' => 'error', 'message' => 'Email send failed: ' . $e->getMessage()]);
}
